### ISSUE TITLE
Dashing

### ISSUE THREAD

**Issue by ristoretto** [Bryan-Legend/metroidvania#5]

**Comment by Bryan-Legend** [comment]
AllowDashHorizontal = owner.Inventory.Has("DashHorizontal");    // needs work
                AllowAirDash = owner.Inventory.Has("AirDash");                  // not implemented
                AllowDashDown = owner.Inventory.Has("DashDown");                // not implemented
                AllowDashUp = owner.Inventory.Has("DashUp");                    // not implemented
                AllowDoubleDash = owner.Inventory.Has("DoubleDash");            // not implemented
                AllowGlide = owner.Inventory.Has("Glide");                      // not implemented
                AllowWallJump = owner.Inventory.Has("WallClimb");               // needs work

**Comment by Bryan-Legend** [comment]
Cut Air Dash

**Comment by Bryan-Legend** [comment]
Dash Up and Dash Down implemented.

**Comment by Bryan-Legend** [comment]
Implemented double dash.

**Comment by Bryan-Legend** [comment]
Implemented Glide

**Comment by Bryan-Legend** [comment]
Fixed wall jump
