### ISSUE TITLE
AI Deaggros

### ISSUE THREAD

**Issue by sarinjthorn** [Bryan-Legend/metroidvania#52]
(to avoid edgecamping player)

**Comment by sarinjthorn** [comment]
deaggros based on the player being a distance, or without LOS for some amount of time, 5 seconds roughly?

**Comment by Bryan-Legend** [comment]
Currently there's no idle movement for enemies. They don't pace or anything so that kind of has to come first.

**Comment by Bryan-Legend** [comment]
Fixed
