### ISSUE TITLE
Secret Tiles disappear upon death

### ISSUE THREAD

**Issue by sarinjthorn** [Bryan-Legend/metroidvania#68]
revealing secrets if you die near them
![image](https://github.com/Bryan-Legend/metroidvania/assets/102440626/4a6089f8-6de6-44ff-9b49-38338ba3aa27)

**Comment by sarinjthorn** [comment]
![image](https://github.com/Bryan-Legend/metroidvania/assets/102440626/f245a2bd-9b64-4e08-a1aa-ba96248f5b0b)

**Comment by Bryan-Legend** [comment]
Fixed
