### ISSUE TITLE
Placeholder block in the editor for multiple types

### ISSUE THREAD

**Issue by ristoretto** [Bryan-Legend/metroidvania#9]

**Comment by Bryan-Legend** [comment]
Hidden Blocks (WIP)
Ice Slopes (WIP)
Lava Blocks
Collapsible Blocks (broken)
One way platform blocks (WIP)
Exploding Blocks (WIP)
Spikes Instant Kill (WIP)
Wind Zones (WIP)

**Comment by Bryan-Legend** [comment]
Pillars (Wishlist)

**Comment by Bryan-Legend** [comment]
Colored Blocks

**Comment by Bryan-Legend** [comment]
Background Images (Wishlist)
Lights (Wishlist)

**Comment by Bryan-Legend** [comment]
Ladders (Wishlist)

**Comment by Bryan-Legend** [comment]
Jump thru platform blocks (WIP)

**Comment by Bryan-Legend** [comment]
Hidden blocks implemented: 
![image](https://user-images.githubusercontent.com/920120/186937443-94cba5d9-490a-402f-af4b-3241c556d5ed.png)

**Comment by Bryan-Legend** [comment]
Added colored blocks. There's a slight performance cost to using them so don't spawn 10k of them.

![image](https://user-images.githubusercontent.com/920120/186948302-21311693-0bd0-43f2-952e-09ef6cfbfbe2.png)

**Comment by Bryan-Legend** [comment]
Stubbed & partly implemented all blocks

![image](https://user-images.githubusercontent.com/920120/186955226-1ccd45e9-9edf-4083-95ed-e0984898e0d3.png)

**Comment by Bryan-Legend** [comment]
Half Blocks (Wishlist)
Glass (WIP)
Red, Green & Yellow (warm) lights (WIP)
Walkthru hidden blocks (WIP)

**Comment by Bryan-Legend** [comment]
Added lights and fixed lighting
![image](https://user-images.githubusercontent.com/920120/186995878-0a3a08f1-a915-4752-8c46-30ee8e8311ca.png)

**Comment by Bryan-Legend** [comment]
Finished glass and walkthru hidden blocks.

**Comment by Bryan-Legend** [comment]
Added half blocks.

![image](https://user-images.githubusercontent.com/920120/186999925-9f77462f-897b-4656-91cb-6a36d1e505e0.png)

**Comment by Bryan-Legend** [comment]
Explosion Blocks Working
![image](https://user-images.githubusercontent.com/920120/187003421-c7aae3da-e08f-4222-af27-52a22f60f7fc.png)
